# Generated by Django 4.2.2 on 2023-12-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FISS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
